In [1]:
# Create list
names = ['ดำ','แดง','ขาว','เขียว','ชมพุ']
age = [10,15,12,14,11]
blood_groups = ['A','A','O','AB','B']
gender = ['ชาย','หญิง','หญิง','หญิง','ชาย']

In [2]:
import pandas as pd
# Create DataFrame
df = pd.DataFrame({'name':names,'age':age,'blood_group':blood_groups,'gender':gender})
df

    name  age blood_group gender
0     ดำ   10           A    ชาย
1    แดง   15           A   หญิง
2    ขาว   12           O   หญิง
3  เขียว   14          AB   หญิง
4   ชมพุ   11           B    ชาย

In [6]:
pd.get_dummies(df, columns=['blood_group','gender'],dtype=int)

,name,age,blood_group_A,blood_group_AB,blood_group_B,blood_group_O,gender_ชาย,gender_หญิง
0,ดำ,10,1,0,0,0,1,0
1,แดง,15,1,0,0,0,0,1
2,ขาว,12,0,0,0,1,0,1
3,เขียว,14,0,1,0,0,0,1
4,ชมพุ,11,0,0,1,0,1,0

In [7]:
# Create New Data list
ชื่อ = ['เอ','บี','ซี','ดี','อี']
ขนาดเสื้อผ้า = ['M','L','S','XL','S']
ช่วงวัย = ['เด็ก','ผู้ใหญ่','วัยรุ่น','สูงอายุ','วัยรุ่น']
ระดับความรุนแรงของอาการ = ['อาการรุนแรง','อาการรุนแรง','ไม่มีอาการ','อาการเล็กน้อย','อาการปานกลาง']
ระดับการศึกษา = ['ประถมศึกษา','ปริญญาตรี','มัธยมศึกษา','ปริญญาเอก','ปริญญาตรี']

# Create DataFrame
df1 = pd.DataFrame({'ชื่อ':ชื่อ,'ขนาดเสื้อผ้า':ขนาดเสื้อผ้า,'ช่วงวัย':ช่วงวัย,'ระดับความรุนแรงของอาการ':ระดับความรุนแรงของอาการ,'ระดับการศึกษา':ระดับการศึกษา})
df1

  ชื่อ ขนาดเสื้อผ้า  ช่วงวัย ระดับความรุนแรงของอาการ ระดับการศึกษา
0   เอ            M     เด็ก             อาการรุนแรง    ประถมศึกษา
1   บี            L  ผู้ใหญ่             อาการรุนแรง     ปริญญาตรี
2   ซี            S  วัยรุ่น              ไม่มีอาการ    มัธยมศึกษา
3   ดี           XL  สูงอายุ           อาการเล็กน้อย     ปริญญาเอก
4   อี            S  วัยรุ่น            อาการปานกลาง     ปริญญาตรี

In [9]:
# Define order of column in DataFrame
order1 = ["S","M","L","XL"]
order2 = ["เด็ก","วัยรุ่น","ผู้ใหญ่","สูงอายุ"]
order3 = ["ไม่มีอาการ","อาการเล็กน้อย","อาการปานกลาง","อาการรุนแรง"]
order4 = ["ประถมศึกษา","มัธยมศึกษา","ปริญญาตรี","ปริญญาเอก"]
df1['ขนาดเสื้อผ้า'] = pd.Categorical(df1['ขนาดเสื้อผ้า'], categories=order1, ordered=True)
df1['ช่วงวัย'] = pd.Categorical(df1['ช่วงวัย'], categories=order2, ordered=True)
df1['ระดับความรุนแรงของอาการ'] = pd.Categorical(df1['ระดับความรุนแรงของอาการ'], categories=order3, ordered=True)
df1['ระดับการศึกษา'] = pd.Categorical(df1['ระดับการศึกษา'], categories=order4, ordered=True)
df1

  ชื่อ ขนาดเสื้อผ้า  ช่วงวัย ระดับความรุนแรงของอาการ ระดับการศึกษา
0   เอ            M     เด็ก             อาการรุนแรง    ประถมศึกษา
1   บี            L  ผู้ใหญ่             อาการรุนแรง     ปริญญาตรี
2   ซี            S  วัยรุ่น              ไม่มีอาการ    มัธยมศึกษา
3   ดี           XL  สูงอายุ           อาการเล็กน้อย     ปริญญาเอก
4   อี            S  วัยรุ่น            อาการปานกลาง     ปริญญาตรี

In [10]:
pd.get_dummies(df1, columns=['ขนาดเสื้อผ้า','ช่วงวัย','ระดับความรุนแรงของอาการ','ระดับการศึกษา'],dtype=int)

,ชื่อ,ขนาดเสื้อผ้า_S,ขนาดเสื้อผ้า_M,ขนาดเสื้อผ้า_L,ขนาดเสื้อผ้า_XL,ช่วงวัย_เด็ก,ช่วงวัย_วัยรุ่น,ช่วงวัย_ผู้ใหญ่,ช่วงวัย_สูงอายุ,ระดับความรุนแรงของอาการ_ไม่มีอาการ,ระดับความรุนแรงของอาการ_อาการเล็กน้อย,ระดับความรุนแรงของอาการ_อาการปานกลาง,ระดับความรุนแรงของอาการ_อาการรุนแรง,ระดับการศึกษา_ประถมศึกษา,ระดับการศึกษา_มัธยมศึกษา,ระดับการศึกษา_ปริญญาตรี,ระดับการศึกษา_ปริญญาเอก
0,เอ,0,1,0,0,1,0,0,0,0,0,0,1,1,0,0,0
1,บี,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0
2,ซี,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0
3,ดี,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1
4,อี,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0

In [14]:
# Exercise filling missing values
# Create list
from pandas import NA

รหัส = ['A001','B001','A005','C007','A003','B002']
เพศ = ['ชาย','ชาย','หญิง',NA,'ชาย', NA]
ส่วนสูง = [150,NA,165,160,155,162]
เกรด = [3.2,2.5,NA,3.9,NA,2.8]
ว่ายน้ำได้หรือไม่ = [NA,'ได้','ไม่ได้',NA,'ไม่ได้','ไม่ได้']

# Create DataFrame
df2 = pd.DataFrame({'รหัส':รหัส,'เพศ':เพศ,'ส่วนสูง':ส่วนสูง,'เกรด':เกรด,'ว่ายน้ำได้หรือไม่':ว่ายน้ำได้หรือไม่})
df2

   รหัส   เพศ ส่วนสูง  เกรด ว่ายน้ำได้หรือไม่
0  A001   ชาย     150   3.2              <NA>
1  B001   ชาย    <NA>   2.5               ได้
2  A005  หญิง     165  <NA>            ไม่ได้
3  C007  <NA>     160   3.9              <NA>
4  A003   ชาย     155  <NA>            ไม่ได้
5  B002  <NA>     162   2.8            ไม่ได้

In [18]:
# Fill missing values with mean
df_imputed = df2.copy()
df_imputed['ส่วนสูง'].fillna(df_imputed['ส่วนสูง'].mean(), inplace=True)
df_imputed['เกรด'].fillna(df_imputed['เกรด'].mean(), inplace=True)

# Fill missing values with mode
df_imputed['เพศ'].fillna(df_imputed['เพศ'].mode()[0], inplace=True)
df_imputed['ว่ายน้ำได้หรือไม่'].fillna(df_imputed['ว่ายน้ำได้หรือไม่'].mode()[0], inplace=True)
df_imputed

   รหัส   เพศ  ส่วนสูง  เกรด ว่ายน้ำได้หรือไม่
0  A001   ชาย    150.0   3.2            ไม่ได้
1  B001   ชาย    158.4   2.5               ได้
2  A005  หญิง    165.0   3.1            ไม่ได้
3  C007   ชาย    160.0   3.9            ไม่ได้
4  A003   ชาย    155.0   3.1            ไม่ได้
5  B002   ชาย    162.0   2.8            ไม่ได้

In [19]:
# Convert categorical data to numerical data
df_imputed['เพศ'] = pd.Categorical(df_imputed['เพศ'], categories=['หญิง','ชาย'], ordered=True)
df_imputed['เพศ'] = df_imputed['เพศ'].cat.codes
df_imputed['ว่ายน้ำได้หรือไม่'] = pd.Categorical(df_imputed['ว่ายน้ำได้หรือไม่'], categories=['ไม่ได้','ได้'], ordered=True)
df_imputed['ว่ายน้ำได้หรือไม่'] = df_imputed['ว่ายน้ำได้หรือไม่'].cat.codes
df_imputed

   รหัส  เพศ  ส่วนสูง  เกรด  ว่ายน้ำได้หรือไม่
0  A001    1    150.0   3.2                  0
1  B001    1    158.4   2.5                  1
2  A005    0    165.0   3.1                  0
3  C007    1    160.0   3.9                  0
4  A003    1    155.0   3.1                  0
5  B002    1    162.0   2.8                  0

In [20]:
# Normalize data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_normalized = df_imputed.copy()
df_normalized[['ส่วนสูง']] = scaler.fit_transform(df_normalized[['ส่วนสูง']])
df_normalized[['เกรด']] = df_normalized[['เกรด']]/4
df_normalized

   รหัส  เพศ   ส่วนสูง   เกรด  ว่ายน้ำได้หรือไม่
0  A001    1  0.000000  0.800                  0
1  B001    1  0.560000  0.625                  1
2  A005    0  1.000000  0.775                  0
3  C007    1  0.666667  0.975                  0
4  A003    1  0.333333  0.775                  0
5  B002    1  0.800000  0.700                  0

In [33]:
# Exercise 2
# Create list
รหัส = ['A001','B001','A005','C007','A003','B002']
เพศ = ['ชาย','ชาย','หญิง',NA,'ชาย', NA]
ส่วนสูง = [150,NA,165,160,155,162]
หมู่เลือด = ['AB','B','O',NA,'O','O']
เกรด = [3.2,2.5,NA,3.9,NA,2.8]
แพ้อาหารหรือไม่ = [NA,'แพ้','ไม่แพ้',NA,'ไม่แพ้','ไม่แพ้']

# Create DataFrame
df3 = pd.DataFrame({'รหัส':รหัส,'เพศ':เพศ,'ส่วนสูง':ส่วนสูง,'หมู่เลือด':หมู่เลือด,'เกรด':เกรด,'แพ้อาหารหรือไม่':แพ้อาหารหรือไม่})
df3

   รหัส   เพศ ส่วนสูง หมู่เลือด  เกรด แพ้อาหารหรือไม่
0  A001   ชาย     150        AB   3.2            <NA>
1  B001   ชาย    <NA>         B   2.5             แพ้
2  A005  หญิง     165         O  <NA>          ไม่แพ้
3  C007  <NA>     160      <NA>   3.9            <NA>
4  A003   ชาย     155         O  <NA>          ไม่แพ้
5  B002  <NA>     162         O   2.8          ไม่แพ้

In [34]:
# Fill missing values 
df3_imputed = df3.copy()
df3_imputed['เพศ'].fillna(df3_imputed['เพศ'].mode()[0], inplace=True)
df3_imputed['ส่วนสูง'].fillna(df3_imputed['ส่วนสูง'].mean(), inplace=True)
df3_imputed['หมู่เลือด'].fillna(df3_imputed['หมู่เลือด'].mode()[0], inplace=True)
df3_imputed['เกรด'].fillna(df3_imputed['เกรด'].mean(), inplace=True)
df3_imputed['แพ้อาหารหรือไม่'].fillna(df3_imputed['แพ้อาหารหรือไม่'].mode()[0], inplace=True)
df3_imputed

   รหัส   เพศ  ส่วนสูง หมู่เลือด  เกรด แพ้อาหารหรือไม่
0  A001   ชาย    150.0        AB   3.2          ไม่แพ้
1  B001   ชาย    158.4         B   2.5             แพ้
2  A005  หญิง    165.0         O   3.1          ไม่แพ้
3  C007   ชาย    160.0         O   3.9          ไม่แพ้
4  A003   ชาย    155.0         O   3.1          ไม่แพ้
5  B002   ชาย    162.0         O   2.8          ไม่แพ้

In [35]:
# Convert categorical data to numerical data
df3_imputed= pd.get_dummies(df3_imputed, columns=['เพศ','หมู่เลือด','แพ้อาหารหรือไม่'],dtype=int)
df3_imputed

,รหัส,ส่วนสูง,เกรด,เพศ_ชาย,เพศ_หญิง,หมู่เลือด_AB,หมู่เลือด_B,หมู่เลือด_O,แพ้อาหารหรือไม่_แพ้,แพ้อาหารหรือไม่_ไม่แพ้
0,A001,150.0,3.2,1,0,1,0,0,0,1
1,B001,158.4,2.5,1,0,0,1,0,1,0
2,A005,165.0,3.1,0,1,0,0,1,0,1
3,C007,160.0,3.9,1,0,0,0,1,0,1
4,A003,155.0,3.1,1,0,0,0,1,0,1
5,B002,162.0,2.8,1,0,0,0,1,0,1

In [36]:
# Normalize data
scaler = MinMaxScaler()
df3_normalized = df3_imputed.copy()
df3_normalized[['ส่วนสูง']] = scaler.fit_transform(df3_normalized[['ส่วนสูง']])
df3_normalized[['เกรด']] = df3_normalized[['เกรด']]/4
df3_normalized

,รหัส,ส่วนสูง,เกรด,เพศ_ชาย,เพศ_หญิง,หมู่เลือด_AB,หมู่เลือด_B,หมู่เลือด_O,แพ้อาหารหรือไม่_แพ้,แพ้อาหารหรือไม่_ไม่แพ้
0,A001,0.000000,0.800,1,0,1,0,0,0,1
1,B001,0.560000,0.625,1,0,0,1,0,1,0
2,A005,1.000000,0.775,0,1,0,0,1,0,1
3,C007,0.666667,0.975,1,0,0,0,1,0,1
4,A003,0.333333,0.775,1,0,0,0,1,0,1
5,B002,0.800000,0.700,1,0,0,0,1,0,1